name: Java with Gradle

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Source Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    # jar file build and permission
    - name: Grant jar
      run: chmod +x gradlew
    - name: Build Jar 
      run: ./gradlew build bootJAR

    # runner(ubuntu) docker buildx install
    - name: Docker buildx
      uses: docker/setup-buildx-action@v2
    
    # docker login
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # docker image build to push dockerhub
    - name: Push image
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/springapp:1.0.0